name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get api_key
        run: echo ${{ secrets.API_KEY }} > apikey.txt
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run project
        run: python main.py

